use twitch_irc::message::PrivmsgMessage;

use super::object::{Emoji, EmojiProperties};

pub fn red_bull(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "Red Bull Cola",
            "Red Bull: Yellow Edition",
            "Red Bull: Orange Edition",
            "Red Bull: Grapefruit Twist Summer Edition",
            "Red Bull: Blue Edition",
            "Red Bull: Green Edition",
            "Red Bull: Red Edition",
            "Red Bull: Coconut Berry Summer Edition",
            "Red Bull: Zero-Calorie Orange Edition",
            "Red Bull: Zero-Calorie Cherry Edition",
            "Red Bull: Sugar-Free Purple Edition",
            "Red Bull: Sugar-Free Lime Edition",
            "Sugar-Free Red Bull",
            "Red Bull Zero",
            "Red Bull: Silver Edition",
        ],
        vec!["ଘ( ˊωˋ )ଓ"],
        Some(1),
        Some(1),
        None,
        None,
        Some(vec!["it gives you wings!"]),
    );
    emo.message(msg, command)
}

pub fn ice_cube(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["ice cubes", "ice spheres", "shards of ice", "ice chunks"],
        vec!["🧊"],
        Some(3),
        Some(12),
        None,
        Some(vec![
            "in a glass",
            "in a cup",
            "still in the ice tray",
            "shaped like Han Solo encased in carbonite",
        ]),
        None,
    );
    emo.message(msg, command)
}

pub fn bottle(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["bottle of milk"],
        vec!["🍼"],
        Some(1),
        Some(1),
        Some(vec![&format!("{} warms up", msg.sender.name)]),
        Some(vec!["to give", "to feed"]),
        Some(vec!["Cry harder!", "Cry more!", "Calm down, child!"]),
    );
    emo.message(msg, command)
}

pub fn milk(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["glasses of milk"],
        vec!["🥛"],
        Some(2),
        Some(8),
        None,
        None,
        Some(vec!["Someone can't take the heat!"]),
    );
    emo.message(msg, command)
}

pub fn coffee(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "cups of coffee",
            "cups of turkish coffee",
            "cups of irish coffee",
            "cups of decaf coffee",
        ],
        vec!["☕"],
        Some(2),
        Some(6),
        None,
        None,
        None,
    );
    emo.message(msg, command)
}

pub fn tea(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["cups of tea"],
        vec!["☕"],
        Some(2),
        Some(5),
        None,
        None,
        None,
    );
    emo.message(msg, command)
}

pub fn green_tea(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["cups of green tea", "cups of matcha tea"],
        vec!["🍵"],
        Some(2),
        Some(4),
        None,
        Some(vec![
            "in a small cup with no handle",
            "in the traditional Japanese teacups",
        ]),
        Some(vec!["It's warm and delicious!"]),
    );
    emo.message(msg, command)
}

pub fn sake(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["cups of sake"],
        vec!["🍶"],
        Some(2),
        Some(4),
        None,
        None,
        Some(vec!["Direct from Japan!"]),
    );
    emo.message(msg, command)
}

pub fn champagne(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["bottle of champagne"],
        vec!["🍾"],
        Some(1),
        Some(1),
        None,
        None,
        Some(vec![
            "They drink it straight from the bottle",
            "Enjoy responsibly!",
        ]),
    );
    emo.message(msg, command)
}

pub fn wine(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["glasses of wine"],
        vec!["🍷"],
        Some(2),
        Some(40),
        None,
        Some(vec!["on a tray", "one by one", "using a toy train"]),
        Some(vec![
            "They're pretty big though.",
            "This should be… interesting.",
        ]),
    );
    emo.message(msg, command)
}

pub fn cocktail(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(vec!["cocktail"], vec!["🍸"], None, None, None, None, None);
    emo.message(msg, command)
}

pub fn martini(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "martini",
            "classic martini",
            "dirty martini",
            "vesper martini",
            "Gibson cocktail martini",
            "French martini",
            "lemon drop martini",
            "cucumber martini",
            "pomegranate martini",
            "watermelon martini",
            "cranberry martini",
            "espresso martini",
            "blood orange martini",
            "Mexican martini",
        ],
        vec!["🍸"],
        None,
        None,
        None,
        None,
        None,
    );
    emo.message(msg, command)
}

pub fn pina_colada(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "pina colada",
            "Miami Vice (half pina colada, half strawberry daquiri)",
        ],
        vec!["🍹"],
        None,
        None,
        None,
        Some(vec!["in a large glass", "in a fancy glass"]),
        None,
    );
    emo.message(msg, command)
}

pub fn daquiri(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "strawberry daquiri",
            "raspberry daquiri",
            "lime daquiri",
            "watermelon daquiri",
            "Hemingway daquiri",
            "banana daquiri",
            "dark rum daquiri",
            "aloe vera daquiri",
            "lemon daquiri",
            "strawberry-lime daquiri",
            "orange-cherry daquiri",
            "gin daquiri (a gimlet)",
            "mint daquiri",
            "grapefruit daquiri",
            "brown derby daquiri",
            "Miami Vice (half pina colada, half strawberry daquiri)",
        ],
        vec!["🍹"],
        None,
        None,
        None,
        Some(vec!["in a large glass", "in a fancy glass"]),
        None,
    );
    emo.message(msg, command)
}

pub fn margarita(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "classic margarita",
            "frozen margarita",
            "highbrow margarita",
            "spicy margarita",
            "watermelon margarita",
            "sweet tea key lime margarita",
            "mojitarita",
            "hibiscus-mint margarita",
            "cranberry margarita",
            "pink Cadillac margarita",
        ],
        vec!["🍹"],
        None,
        None,
        None,
        Some(vec!["in a large glass", "in a fancy glass"]),
        None,
    );
    emo.message(msg, command)
}

pub fn tropical_drink(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "fancy tropical drink",
            "fruity drink with a tiny umbrella",
            "Miami Vice (half pina colada, half strawberry daquiri)",
        ],
        vec!["🍹"],
        None,
        None,
        None,
        Some(vec![
            "in a large glass",
            "in a fancy glass",
            "in a fishbowl",
        ]),
        None,
    );
    emo.message(msg, command)
}

pub fn beer(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["ice-cold beers"],
        vec!["🍺"],
        Some(2),
        Some(24),
        None,
        Some(vec!["in near-frozen mugs", "with frothy head"]),
        Some(vec!["Enjoy!"]),
    );
    emo.message(msg, command)
}

pub fn cheers(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["'Cheers!'", "'Salut!'", "'Prost!'", "'L'chaim!'"],
        vec!["🥃"],
        Some(1),
        Some(1),
        None,
        Some(vec!["in celebration", "in recognition of their glory"]),
        Some(vec!["CONGRATULATIONS!", ""]),
    );
    emo.message(msg, command)
}

pub fn stiff_drink(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "stiff drink",
            "cup o' booze",
            "glass of whiskey",
            "Manhattan with a brandied cherry",
            "smoked Old Fashioned with an orange zest twist",
            "Rob Roy with an orange zest twist and a maraschino cherry",
            "Red Lion in a glass with a sugar-coated rim",
        ],
        vec!["🥃"],
        None,
        None,
        None,
        Some(vec!["with a block of ice 🧊", "straight up"]),
        None,
    );
    emo.message(msg, command)
}

pub fn whiskey(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "glass of whiskey",
            "Manhattan with a brandied cherry",
            "smoked Old Fashioned with an orange zest twist",
            "Rob Roy with an orange zest twist and a maraschino cherry",
            "Red Lion in a glass with a sugar-coated rim",
            "glass of Forty Creek",
            "glass of Jack Daniel's",
        ],
        vec!["🥃"],
        None,
        None,
        None,
        Some(vec!["with a block of ice 🧊", "straight up"]),
        None,
    );
    emo.message(msg, command)
}

pub fn solo_cup(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["solo cups"],
        vec!["🥤"],
        Some(3),
        Some(149),
        Some(vec!["{sender} points out"]),
        None,
        Some(vec!["You should clean up this room.", "", ""]),
    );
    emo.message(msg, command)
}

pub fn soft_drink(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec![
            "7Up Cherry",
            "7Up Diet Cherry",
            "7Up Diet",
            "7Up PLUS Cherry",
            "7Up PLUS Island Fruit",
            "7Up PLUS Mixed Berry",
            "7Up",
            "A-Treat Big Blue",
            "A-Treat Birch Beer",
            "A-Treat Black Cherry",
            "A-Treat Blue Razz",
            "A-Treat Cola",
            "A-Treat Cream Soda",
            "A-Treat Diet Birch Beer",
            "A-Treat Diet Cream Soda",
            "A-Treat Diet Ginger Ale",
            "A-Treat Ginger Ale",
            "A-Treat Grapefruit",
            "A-Treat Orange Cream",
            "A-Treat Orange",
            "A-Treat Root Beer",
            "A-Treat Sarsaparilla",
            "A&W Cream Soda",
            "A&W Diet Cream Soda",
            "A&W Diet Root Beer",
            "A&W Root Beer",
            "Ale 8 Cherry",
            "Ale-8 Diet Caffeine Free",
            "Ale-8 Diet",
            "Ale-8 Orange Cream",
            "Ale-8-One",
            "Barq's Birch Beer",
            "Barq's Crème Soda",
            "Barq's Diet French Vanilla Crème Soda",
            "Barq's Diet Red Crème Soda",
            "Barq's Diet Root Beer",
            "Barq's Floatz",
            "Barq's French Vanilla Crème Soda",
            "Barq's Red Crème Soda",
            "Blue Sky Black Cherry",
            "Blue Sky Cherry Vanilla",
            "Blue Sky Cola",
            "Blue Sky Cream Soda",
            "Blue Sky Dr Becker",
            "Blue Sky Ginger Ale",
            "Blue Sky Lemon Lime",
            "Blue Sky Root Beer",
            "Boylan Black Cherry",
            "Boylan Cane Cola",
            "Boylan Classic Seltzer",
            "Boylan Club Soda ... I hope you brought your own mixer",
            "Boylan Creamy Red Birch Beer",
            "Boylan Creme Soda",
            "Boylan Diet Black Cherry",
            "Boylan Diet Cane Cola",
            "Boylan Diet Creme Soda",
            "Boylan Diet Ginger Ale",
            "Boylan Diet Root Beer",
            "Boylan Ginger Ale",
            "Boylan Ginger Beer",
            "Boylan Grape",
            "Boylan Lemon Seltzer",
            "Boylan Lime Seltzer",
            "Boylan Orange",
            "Boylan Original Birch Beer",
            "Boylan Raspberry Seltzer",
            "Boylan Root Beer",
            "Boylan Shirley Temple",
            "Boylan Sparkling Lemonade",
            "Boylan Tonic Water... but why?",
            "Caleb's Kola",
            "Canada Dry Blackberry Ginger Ale",
            "Canada Dry Club Soda",
            "Canada Dry Cranberry Ginger Ale",
            "Canada Dry Diet Ginger Ale",
            "Canada Dry Ginger Ale and Lemonade",
            "Canada Dry Ginger Ale",
            "Canada Dry Green Tea Ginger Ale",
            "Canada Dry Lemon Lime Club Soda",
            "Canada Dry Orange Mandarin Club Soda",
            "Canada Dry Pomegranate Cherry Club Soda",
            "Canada Dry Tonic",
            "Cheerwine Caffeine-free Diet",
            "Cheerwine Diet",
            "Cheerwine Holiday Punch",
            "Cheerwine Kreme",
            "Cheerwine Retro",
            "Cheerwine",
            "Coca-Cola (Mexican)",
            "Coca-Cola Black Cherry Vanilla",
            "Coca-Cola Black Cherry",
            "Coca-Cola Blak",
            "Coca-Cola Cherry",
            "Coca-Cola Cinnamon",
            "Coca-Cola Citra",
            "Coca-Cola Diet Caffeine-Free",
            "Coca-Cola Diet Feisty Cherry",
            "Coca-Cola Diet Ginger Lime",
            "Coca-Cola Diet Lime",
            "Coca-Cola Diet Strawberry Guava",
            "Coca-Cola Diet Twisted Mango",
            "Coca-Cola Diet with Cherry",
            "Coca-Cola Diet",
            "Coca-Cola Life",
            "Coca-Cola Lime",
            "Coca-Cola New (New Coke)",
            "Coca-Cola No Sugar",
            "Coca-Cola Orange",
            "Coca-Cola Raspberry",
            "Coca-Cola Vanilla",
            "Coca-Cola Winter Spiced Cranberry",
            "Coca-Cola with Lemon",
            "Coca-Cola Zero Cherry",
            "Coca-Cola Zero Lime",
            "Coca-Cola Zero",
            "Coca-Cola Zesty Blood Orange",
            "Coca-Cola",
            "Crush Apple",
            "Crush Banana",
            "Crush Berry Blast",
            "Crush Berry Pomegranate",
            "Crush Berry Punch",
            "Crush Birch Beer",
            "Crush Blue Raspberry",
            "Crush Bubblegum Slush ",
            "Crush Cherry",
            "Crush Chocolate",
            "Crush Cola",
            "Crush Cream Soda",
            "Crush Diet Apple",
            "Crush Diet Cream Soda",
            "Crush Diet Grape",
            "Crush Diet Lime",
            "Crush Diet Orange",
            "Crush Frozen Orange Dream",
            "Crush Fruity Red",
            "Crush Ginger Beer",
            "Crush Grape",
            "Crush Grapefruit",
            "Crush Lemon-Lime",
            "Crush Lemon",
            "Crush Lemonade",
            "Crush Lime Rickey",
            "Crush Lime",
            "Crush Nectar",
            "Crush Orange Dry",
            "Crush Orange Light",
            "Crush Orange",
            "Crush Peach Sour",
            "Crush Peach",
            "Crush Pear",
            "Crush Pineapple",
            "Crush Pink Grapefruit",
            "Crush Red Cream",
            "Crush Red Licorice",
            "Crush Root Beer",
            "Crush Sarsi",
            "Crush Soda Water",
            "Crush Sour Apple",
            "Crush Spruce Beer",
            "Crush Strawberries 'n' Cream",
            "Crush Strawberry Lemonade",
            "Crush Strawberry",
            "Crush Tropical Punch",
            "Crush Tuti-Fruti",
            "Crush Watermelon",
            "Crush Wild Cherry Cola",
            "Dr Pepper and Cream Soda",
            "Dr Pepper Caffeine-free",
            "Dr Pepper Cherry Vanilla",
            "Dr Pepper Cherry",
            "Dr Pepper Diet and Cream Soda",
            "Dr Pepper Diet Caffeine-free",
            "Dr Pepper Diet Cherry Vanilla",
            "Dr Pepper Diet Cherry",
            "Dr Pepper Diet",
            "Dr Pepper Made with Sugar",
            "Dr Pepper TEN",
            "Dr Pepper",
            "Dr. Brown's Black Cherry",
            "Dr. Brown's Cel Ray",
            "Dr. Brown's Cream Soda",
            "Dr. Brown's Diet Black Cherry",
            "Dr. Brown's Diet Cream Soda",
            "Dr. Brown's Ginger Ale",
            "Dr. Brown's Orange",
            "Dr. Brown's Root Beer",
            "Dry Sparkling Cucumber",
            "Dry Sparkling Ginger",
            "Dry Sparkling Ranier Cherry",
            "Dry Sparkling Vanilla Bean",
            "Fanta Apple",
            "Fanta Berry",
            "Fanta Birch Beer",
            "Fanta Blue Raspberry",
            "Fanta Blue Vanilla",
            "Fanta Bubble Gum Slurpee",
            "Fanta Cherry Limeade",
            "Fanta Cherry",
            "Fanta Clear Apple",
            "Fanta Clear Pineapple",
            "Fanta Cream Soda",
            "Fanta Fresh Apple",
            "Fanta Fruit Punch",
            "Fanta Funmix",
            "Fanta Golden Grape",
            "Fanta Grape",
            "Fanta Grapefruit",
            "Fanta Green Apple",
            "Fanta Green Soda",
            "Fanta Green",
            "Fanta Honey Lemon",
            "Fanta Iced Tea",
            "Fanta Icy Lemon Lime",
            "Fanta Icy Lemon",
            "Fanta Lactic",
            "Fanta Lemon",
            "Fanta Lime",
            "Fanta Lite Mango Lemonade Slurpee",
            "Fanta Lite Pineapple Coconut Lime Slurpee",
            "Fanta Lite Strawberry Banana Slurpee",
            "Fanta Lite Watermelon Punch Slurpee",
            "Fanta Love Berry",
            "Fanta Mango",
            "Fanta Melon Cream",
            "Fanta Melon Frosty",
            "Fanta Moo Moo White",
            "Fanta Muscat",
            "Fanta Nashi",
            "Fanta Orange",
            "Fanta Otona Peach",
            "Fanta Otona Pear",
            "Fanta Papaya",
            "Fanta Party-Mix Muscat and Apple",
            "Fanta Peach",
            "Fanta Pina Colada",
            "Fanta Pineapple",
            "Fanta Pomegranate",
            "Fanta Raspberry",
            "Fanta Red Tangerine",
            "Fanta Salty Watermelon",
            "Fanta Sour Grape Slurpee",
            "Fanta Sour Green Apple Slurpee",
            "Fanta Sour Orange Slurpee",
            "Fanta Spider Chocolate Orange",
            "Fanta Starfruit",
            "Fanta Strawberry Cream",
            "Fanta Strawberry",
            "Fanta Tropical Mango",
            "Fanta Tropical Yogurt",
            "Fanta Ultra Lemon",
            "Fanta Ume",
            "Fanta Vanilla Ice Cream",
            "Fanta Watermelon Lime Slurpee",
            "Fanta White Banana",
            "Fanta White Strawberry",
            "Fanta Wild Cherry",
            "Fanta Yuzu",
            "Fanta Zero Cherry",
            "Fanta Zero Cider",
            "Fanta Zero Fruit Punch",
            "Fanta Zero Grape",
            "Fanta Zero Lime",
            "Fanta Zero Orange",
            "Fanta Zero Peach",
            "Fanta Zero Raspberry",
            "Fanta Zero Strawberry",
            "Fanta Zero Vanilla",
            "Fanta Zesty Berry",
            "Fanta",
            "Fresca Black Cherry Citrus",
            "Fresca Original Citrus",
            "Fresca Peach Citrus",
            "Hansen's Cherry Vanilla",
            "Hansen's Diet Black Cherry",
            "Hansen's Diet Cherry Vanilla",
            "Hansen's Diet Ginger Ale",
            "Hansen's Diet Original Cola",
            "Hansen's Diet Root Beer",
            "Hansen's Ginger Ale",
            "Hansen's Grapefruit",
            "Hansen's Key Lime Twist",
            "Hansen's Kiwi Strawberry",
            "Hansen's Mandarin Lime",
            "Hansen's Orange",
            "Hansen's Original Cola",
            "Hansen's Pomegranate",
            "Hansen's Root Beer",
            "Hansen's Vanilla Cola",
            "Hires Root Beer",
            "IBC Root Beer",
            "Irn-Bru Sugar Free",
            "Irn-Bru",
            "Jarritos Fruit Punch",
            "Jarritos Grapefruit Soda",
            "Jarritos Guava Soda",
            "Jarritos Jamaica Soda",
            "Jarritos Lemon Lime Soda",
            "Jarritos Lime Soda",
            "Jarritos Mandarin Soda",
            "Jarritos Mango Soda",
            "Jarritos Mexican cola",
            "Jarritos Pineapple Soda",
            "Jarritos Strawberry Soda",
            "Jarritos Tamarind Soda",
            "Jarritos Watermelon Soda",
            "Jones Berry Lemonade",
            "Jones Blue Bubblegum",
            "Jones Cola",
            "Jones Cream Soda",
            "Jones Crushed Melon",
            "Jones Fufu Berry",
            "Jones Grape",
            "Jones Green Apple",
            "Jones Lemon Lime",
            "Jones Orange & Cream",
            "Jones Pineapple Cream",
            "Jones Root Beer",
            "Jones Strawberry Lime",
            "Jones Zilch black Cherry",
            "Jones Zilch Cola",
            "Kick",
            "Maine Root. Blueberry",
            "Maine Root. Fair Trade Lemonade",
            "Maine Root. Ginger Brew",
            "Maine Root. Ginger-Lemongrass Lemonade",
            "Maine Root. Lemon Lime",
            "Maine Root. Mandarin Orange",
            "Maine Root. Maple Syrup Lemonade",
            "Maine Root. Mexicane Cola",
            "Maine Root. Pumpkin Pie",
            "Maine Root. Root Beer",
            "Maine Root. Sarsparilla",
            "Mello Yello (Lift if you're Australian)",
            "Mello Yello Afterglow",
            "Mello Yello Cherry",
            "Mello Yello Melon",
            "Mountain Dew Baja Blast Zero Sugar",
            "Mountain Dew Baja Blast",
            "Mountain Dew Code Red",
            "Mountain Dew Diet",
            "Mountain Dew Ice",
            "Mountain Dew Kickstart Black Cherry",
            "Mountain Dew Kickstart Mango Lime",
            "Mountain Dew Live Wire",
            "Mountain Dew Pitch Black",
            "Mountain Dew Sweet Lightning",
            "Mountain Dew Throwback",
            "Mountain Dew Voltage",
            "Mountain Dew White Out",
            "Mountain Dew",
            "Moxie (Maine's official soft drink)",
            "Mug Cream Soda",
            "Mug Diet Root Beer",
            "Mug Root Beer",
            "Norka Cherry-Strawberry",
            "Norka Giner Ale",
            "Norka Natural Lemon Lime",
            "Norka Orange",
            "Norka Root Beer",
            "Nuka Cherry",
            "Nuka Cola Dark",
            "Nuka Cola Orange",
            "Nuka Cola Quantum",
            "Nuka Cola Quartz",
            "Nuka Cola Victory",
            "Nuka Cola Wild",
            "Nuka Cola",
            "Nuka Grape",
            "Orangina Indien",
            "Orangina Light",
            "Orangina RastaMan",
            "Orangina Rouge",
            "Orangina Samourai",
            "Orangina Sanguine",
            "Orangina",
            "Pecsi",
            "Pepsi 100",
            "Pepsi 1893 Citrus Cola",
            "Pepsi 1893 Ginger Cola",
            "Pepsi 1893 Original Cola",
            "Pepsi 1983 Black Currant Cola",
            "Pepsi Advantage",
            "Pepsi Aha",
            "Pepsi AM",
            "Pepsi Azuki",
            "Pepsi Baobab",
            "Pepsi Berry",
            "Pepsi Black",
            "Pepsi Blue Chilled Cols",
            "Pepsi Blue Hawaii",
            "Pepsi Blue",
            "Pepsi Boom",
            "Pepsi Caffeine Free",
            "Pepsi Candy",
            "Pepsi Cappuccino",
            "Pepsi Capuchino",
            "Pepsi Caribbean Gold",
            "Pepsi Carnival",
            "Pepsi Cheer",
            "Pepsi Cherry Vanilla",
            "Pepsi Christmas Cola",
            "Pepsi Christmas",
            "Pepsi Clear",
            "Pepsi Cream",
            "Pepsi Crystal",
            "Pepsi Diet AM",
            "Pepsi Diet Caffeine-Free",
            "Pepsi Diet Cherry Vanilla",
            "Pepsi Diet Crystal",
            "Pepsi Diet Kickoff",
            "Pepsi Diet Kona",
            "Pepsi Diet Lemon",
            "Pepsi Diet Light",
            "Pepsi Diet Lime",
            "Pepsi Diet Twist",
            "Pepsi Diet Twistão",
            "Pepsi Diet Vanilla",
            "Pepsi Diet Wild Cherry",
            "Pepsi Diet with Splenda",
            "Pepsi Diet",
            "Pepsi Dry",
            "Pepsi Edge",
            "Pepsi Extra",
            "Pepsi Fire",
            "Pepsi Free",
            "Pepsi Freeze",
            "Pepsi Fresh",
            "Pepsi Ghost",
            "Pepsi Ginga",
            "Pepsi Ginger",
            "Pepsi Gold",
            "Pepsi Green",
            "Pepsi Halloween Cola",
            "Pepsi Holiday Spice",
            "Pepsi Ice Cream",
            "Pepsi Ice Cucumber",
            "Pepsi Ice",
            "Pepsi Jaffa",
            "Pepsi Jazz Black Cherry French Vanilla",
            "Pepsi Jazz Caramel Cream",
            "Pepsi Jazz Coffee Mousse",
            "Pepsi Jazz Strawberries and Cream",
            "Pepsi Kaffe",
            "Pepsi Kick",
            "Pepsi Kona",
            "Pepsi La Liga",
            "Pepsi Latte",
            "Pepsi Lemon",
            "Pepsi Light Lima",
            "Pepsi Light Mojito",
            "Pepsi Light Twist",
            "Pepsi Light",
            "Pepsi Lime",
            "Pepsi Limón",
            "Pepsi Mango",
            "Pepsi Max Cease Fire",
            "Pepsi Max Cherry",
            "Pepsi Max Chill",
            "Pepsi Max Cino",
            "Pepsi Max Citron Citron Vert",
            "Pepsi Max Citrus Freeze",
            "Pepsi Max Cool Lemon",
            "Pepsi Max Creaming Soda",
            "Pepsi Max Diet",
            "Pepsi Max Energy",
            "Pepsi Max Ginger",
            "Pepsi Max Gold",
            "Pepsi Max Lime",
            "Pepsi Max Mango",
            "Pepsi Max Mojito",
            "Pepsi Max Mojo",
            "Pepsi Max Punch",
            "Pepsi Max Twist",
            "Pepsi Max Vanilla",
            "Pepsi Max Wild Side",
            "Pepsi Mojito",
            "Pepsi Mont Blanc",
            "Pepsi NEX",
            "Pepsi Next Cherry Vanilla",
            "Pepsi Next Paradise Mango",
            "Pepsi Next",
            "Pepsi ONE",
            "Pepsi Peach",
            "Pepsi Pinas",
            "Pepsi Pineapple",
            "Pepsi Pink",
            "Pepsi Pogi",
            "Pepsi Punch",
            "Pepsi Raging Raspberry",
            "Pepsi Raspberry",
            "Pepsi Raw",
            "Pepsi Real Sugar",
            "Pepsi Red",
            "Pepsi Retro",
            "Pepsi Sakura",
            "Pepsi Salted Caramel",
            "Pepsi Salty Watermelon",
            "Pepsi Samba",
            "Pepsi Shiso",
            "Pepsi Special Lemon Mint",
            "Pepsi Special",
            "Pepsi Strawberry Burst",
            "Pepsi Strong Shot",
            "Pepsi Strong",
            "Pepsi Sugar Free",
            "Pepsi Summer Chill",
            "Pepsi Summer Mix",
            "Pepsi Tarik",
            "Pepsi Throwback",
            "Pepsi Tropical Chill",
            "Pepsi Tropical",
            "Pepsi Twist 3",
            "Pepsi Twist Mojito",
            "Pepsi Twist Zero",
            "Pepsi Twist",
            "Pepsi Twistão",
            "Pepsi Vanilla",
            "Pepsi White",
            "Pepsi Wild Cherry",
            "Pepsi X - 2012",
            "Pepsi X Energy Cola",
            "Pepsi X",
            "Pepsi XL",
            "Pepsi",
            "Pibb Xtra",
            "RC 100 Sugar Free",
            "RC 100",
            "RC Cherry",
            "RC Cola Classic",
            "RC Cola Edge",
            "RC Cola Lemon",
            "RC Cola Zero",
            "RC Cola",
            "RC Diet Cherry",
            "RC Diet Cola Lemon",
            "RC Diet Cola",
            "RC Dra-Cola",
            "RC Draft Cola",
            "RC Kick",
            "RC Ten",
            "Reed's Ginger Ale",
            "Reed's Ginger Beer Extra",
            "Reed's Ginger Beer Original",
            "Reed's Ginger Beer Strongest",
            "Reed's Ginger Beer Zero-Sugar Extra",
            "Reed's Ginger Beer Zero-Sugar",
            "Roxa-Kola",
            "Schweppes Club Soda (grab some mixer)",
            "Schweppes Cranberry Raspberry Ginger Ale",
            "Schweppes Diet Ginger Ale",
            "Schweppes Ginger Ale",
            "Schweppes Tonic Water (you know, for the malaria)",
            "Schweppes Zero Sugar Blood Orange",
            "Schweppes Zero Sugar Grapefruit",
            "Seagram's Club Soda",
            "Seagram's Diet Ginger Ale",
            "Seagram's Diet Tonic Water",
            "Seagram's Ginger Ale",
            "Seagram's Seltzer Water",
            "Seagram's Tonic Water",
            "Sierra Mist Natural Lemon-Lime Soda, Made with Real Sugar",
            "Sprite Cherry Zero Sugar",
            "Sprite Cherry",
            "Sprite Ginger Zero Sugar",
            "Sprite Ginger",
            "Sprite Lymonade",
            "Sprite Tropical Mix",
            "Sprite Zero Sugar",
            "Sprite",
            "Squirt Grapefruit Soda",
            "Stewart's Birch Beer Soda",
            "Stewart's Cherries 'n Cream Soda",
            "Stewart's Cream Soda",
            "Stewart's Diet Orange 'n Cream Soda",
            "Stewart's Diet Root Beer",
            "Stewart's Grape Soda",
            "Stewart's Key Lime Soda",
            "Stewart's Orange 'n Cream Soda",
            "Stewart's Root Beer",
            "Stewart's Wishniak Black Cherry",
            "Sun Drop Caffeine Free",
            "Sun Drop Cherry Lemon Citrus",
            "Sun Drop",
            "Sunkist Cherry Limeade",
            "Sunkist Diet Lemonade",
            "Sunkist Diet Orange",
            "Sunkist Fruit Punch",
            "Sunkist Grape",
            "Sunkist Lemonade",
            "Sunkist Orange",
            "Sunkist Peach",
            "Sunkist Pineapple",
            "Sunkist Pink Lemonade",
            "Sunkist Strawberry Lemonade",
            "Sunkist Strawberry",
            "Surge",
            "Vernors Ginger Soda",
            "Virgil's Handcrafted Black Cherry",
            "Virgil's Handcrafted Orange Soda",
            "Virgil's Handcrafted Root Beer",
            "Virgil's Handcrafted Vanilla Cream Soda",
            "Virgil's Zero Sugar Black Cherry",
            "Virgil's Zero Sugar Cola",
            "Virgil's Zero Sugar Lemon Lime",
            "Virgil's Zero Sugar Orange",
            "Virgil's Zero Sugar Root Beer",
            "Virgil's Zero Sugar Vanilla Cream Soda",
        ],
        vec![],
        None,
        None,
        None,
        Some(vec![
            "with a straw",
            "in a can",
            "in a bottle",
            "from the fountain drink machine",
        ]),
        Some(vec![
            "🥤 It's cold! 🧊",
            "🥤 It's icy! 🧊🧊🧊🧊",
            "🥤 It's room-temperature. 🔥",
            "🥤 It's been sitting in the sun. 🔥🔥",
            "🥤 It's empty!",
            "🥤 It's half-empty!",
            "🥤 It's very cold! 🧊🧊",
            "🥤 It's very very cold! 🧊🧊🧊",
        ]),
    );
    emo.message(msg, command)
}

pub fn juice_box(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["juice boxes", "Capri Suns", "Sunny D juice boxes"],
        vec![],
        Some(2),
        Some(6),
        None,
        Some(vec!["", "in a lunch box"]),
        None,
    );
    emo.message(msg, command)
}

pub fn yerba_mate(msg: &PrivmsgMessage, command: &str) -> String {
    let emo = Emoji::new(
        vec!["serving of green yerba mate"],
        vec!["🧉"],
        Some(1),
        Some(1),
        None,
        Some(vec!["in a coconut", "with a metal straw"]),
        None,
    );
    emo.message(msg, command)
}
